import {
  FaRocket, FaFileCode, FaKey, FaLock, FaRandom,
  FaSearch, FaClock, FaPalette, FaShieldAlt, FaCompress,
  FaQrcode, FaDatabase, FaCode,
} from 'react-icons/fa';
import type { ToolDefinition } from './types';

export const toolDefinitions: ToolDefinition[] = [
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Test HTTP endpoints with custom methods, headers, and body',
    icon: FaRocket,
    category: 'development',
    shortcut: 'Ctrl+1',
    keywords: ['http', 'request', 'rest', 'api', 'endpoint', 'fetch', 'curl'],
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data',
    icon: FaCode,
    category: 'formatting',
    shortcut: 'Ctrl+2',
    keywords: ['json', 'format', 'validate', 'minify', 'beautify'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens without validation',
    icon: FaKey,
    category: 'security',
    shortcut: 'Ctrl+3',
    keywords: ['jwt', 'token', 'decode', 'header', 'payload', 'auth'],
  },
  {
    id: 'base64',
    name: 'Base64',
    description: 'Encode and decode Base64 strings',
    icon: FaLock,
    category: 'conversion',
    shortcut: 'Ctrl+4',
    keywords: ['base64', 'encode', 'decode', 'base64url'],
  },
  {
    id: 'uuid',
    name: 'UUID Generator',
    description: 'Generate UUID v4 identifiers in bulk',
    icon: FaRandom,
    category: 'generation',
    shortcut: 'Ctrl+5',
    keywords: ['uuid', 'guid', 'generate', 'identifier'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions against sample text',
    icon: FaSearch,
    category: 'development',
    shortcut: 'Ctrl+6',
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test'],
  },
  {
    id: 'timestamp',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    icon: FaClock,
    category: 'conversion',
    shortcut: 'Ctrl+7',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert'],
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and convert between HEX, RGB, HSL formats',
    icon: FaPalette,
    category: 'development',
    keywords: ['color', 'picker', 'hex', 'rgb', 'hsl', 'palette'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes',
    icon: FaShieldAlt,
    category: 'security',
    keywords: ['hash', 'sha', 'sha1', 'sha256', 'sha512', 'hmac'],
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images with quality control and preview',
    icon: FaCompress,
    category: 'development',
    keywords: ['image', 'compress', 'resize', 'optimize', 'png', 'jpeg'],
  },
  {
    id: 'qr-generator',
    name: 'QR Generator',
    description: 'Generate QR codes from text or URLs',
    icon: FaQrcode,
    category: 'generation',
    keywords: ['qr', 'qrcode', 'barcode', 'scan', 'generate'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong passwords with custom rules',
    icon: FaLock,
    category: 'security',
    keywords: ['password', 'generate', 'secure', 'random', 'strength'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries',
    icon: FaDatabase,
    category: 'formatting',
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
  },
];

export const toolCategories: { id: ToolCategory; label: string }[] = [
  { id: 'development', label: 'Development' },
  { id: 'conversion', label: 'Conversion' },
  { id: 'security', label: 'Security' },
  { id: 'generation', label: 'Generation' },
  { id: 'formatting', label: 'Formatting' },
];
